### ISSUE TITLE
Usage: combining queries

### ISSUE THREAD

**Issue by myselfhimself** [iverberk/larasearch#23]
Hello,

Thank you again very much for the Larasearch library.

I would like to query for documents having altogether : 
- given keywords within a set of analyzed fields,
- some_field = NN,
- some_other_field = NN
- .. etc.

The first bullet is doable natively by following the examples in README.md.

For combining with other bullets it does not seem so. Looking at `Query->getPayload()` which is one of Larasearch's last step before telling the ES PHP Client to search, it does not seem feasible for now to have more queries within the dismax handler than the existing series of lookup for `$this->term` within the given analyzed fields.

How is that possible to search for multiple terms in different fields in Larasearch ?

**Comment by smithdp1** [comment]
actually this works for me.

```
$params['match']['YOUR_COLUMN'] = $YOURVAR;
$results = YOUR_MODEL::search(\Input::get('q', '*'), $params);
```
