### ISSUE TITLE
Response->getRecords() does not keep retrieved ids orders

### ISSUE THREAD

**Issue by myselfhimself** [iverberk/larasearch#29]
Hello,

When adding an `order` param to ElasticSearch, the retrieved is most probably correctly orderer. However, larasearch's Response->getRecords() uses Eloquent's `whereIn('id', $ids)->get()` which does not care about ids order anymore.
Expected behaviour would be to return the records in the order as they are retrieved from ElasticSearch.

Here's a related LaravelSnippet that "could" fix it though larasearch is meant to be database-agnostic:
http://laravelsnippets.com/snippets/get-all-items-at-once-ordered-by-the-current-order-of-ids-in-the-where-in-clause-using-eloquent

I may later propose soon a patch providing a `Response->getRecordsQuery()` that yields an Eloquent Query `Builder` and allows for finer tuning before `->get()`'ing results.

**Comment by iverberk** [comment]
@myselfhimself I think this should be documented somewhere but necessarily included in Larasearch. Should I make an entry in the documentation wiki with this trait for people who want to use it?

Also, the "I may later propose soon a patch providing a Response->getRecordsQuery() that yields an Eloquent Query Builder and allows for finer tuning before ->get()'ing results." seems really interesting. Did you follow through with it?

**Comment by myselfhimself** [comment]
Hello @iverberk you can do what you want with the piece of code. I had myself got inspiration for it on some other website or blog I cannot remember.

I think that I had not added a getRecordsQuery() to Larasearch, but just that Trait above. I am not working on a ES project currently so it is better that you add what seems interesting to you in larasearch´s code yourself.

Thank you for your hard work and good library!

**Comment by iverberk** [comment]
Thanks for the feedback. I will close the issue for now. It will be available as a reference and maybe I'll add it to the code when I need it :-)
