### ISSUE TITLE
Auto index base model

### ISSUE THREAD

**Issue by marijang** [iverberk/larasearch#32]
I want to reindex User model when i update user for example

This is my User model

```
class User extends SentryUserModel {

  use Iverberk\Larasearch\Traits\SearchableTrait;

```

How to get auto reindex?

**Comment by kJamesy** [comment]
+1

**Comment by smithdp1** [comment]
so what is solution to this??? I get same error.

**Comment by ferrydg** [comment]
You need not include the CallableTrait because it's already included by the SearchableTrait and thus twice included which causes the collision.

**Comment by Huthayfa-Malhas** [comment]
It worked for me after adding the following to SearchableTrait:

``` php
    public static function bootSearchableTrait()
    {
        parent::bootCallableTrait();
    }
```
