### ISSUE TITLE
Issues I can't seem to figure out

### ISSUE THREAD

**Issue by feenx** [iverberk/larasearch#34]
Hello all!

So I've implemented Larasearch into my library hosted at www.gamejerks.net and I'm having issues. I have several different object types such as Reviews, Articles, Games, Videos and Users. I have no issue indexing and searching against all the types except for Games. Obviously that doesn't help anyone but what I'm trying to figure out is whether or not I can figure out what may be tripping up the artisan command to reindex because I receive the error:

```
[Iverberk\Larasearch\Exceptions\ImportException]
  Bulk import with errors
```

And I can't seem to figure out why. The model Game has 3,000 records so I can't really go through them and try it out, only thing I can think of is that the error occurs while it still reads "\* Batch 1" so I'm assuming that means the problem is within the first 750 records that are being indexed.

**Comment by kJamesy** [comment]
Just a note that changing my column structure from longText to mediumText fixed this issue for me.

**Comment by kJamesy** [comment]
Just a note that changing my column structure from longText to mediumText fixed this issue for me. 

Alternatively, in config, changing mappings > _default_ > dynamic_templates > string_template > {name} > type to binary does the trick.
