### ISSUE TITLE
Only flag Model for reindex when certain fields change versus when any do

### ISSUE THREAD

**Issue by pfeiferchristopher** [iverberk/larasearch#39]
So I have my User model indexed with Larasearch, and I'm having issues where during a login process because of how several things are changed, each time triggering a different "save" it causes on average 7-8 reindex Queue jobs for that User record. Even though nothing important or that I'm indexing changed.

How would you suggest going about limiting the Observer to only flag something for reindex if certain fields had changed? I thought perhaps using `self::updating()` instead but that would be triggered the every time as well.

**Comment by iverberk** [comment]
I created a wiki entry [here](https://github.com/iverberk/larasearch/wiki/Automatic-reindexing) that describes in more detail how to implement this.

**Comment by iverberk** [comment]
Unless any further actions is required I'm closing this issue for now.
