### ISSUE TITLE
Add relations

### ISSUE THREAD

**Issue by jbonigomes** [iverberk/larasearch#42]
Apologies for the noob question, but I can't get the reindex command to run correctly, I have a model that is called Sitemap, I can run the following with no problems:

```
    $ php artisan larasearch:paths Sitemap --relations

    {
        "paths": {
            "Sitemap": [
                "article"
            ]
        },
        "reversedPaths": {
            "Sitemap": [
                ""
            ],
            "Article": [
                "sitemap"
            ]
        }
    }
```

However, when I run:

```
    $ php artisan larasearch:reindex Sitemap --relations --dir=app/models
```

I get the following error:

```
    [ErrorException]
      Argument 1 passed to Illuminate\Database\Eloquent\Builder::parseRelations() must be of the type array, null given, call
      ed in /home/vagrant/cybercms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php on line 717 and defi
      ned
```

Any direction would be much appreciated, thanks.

**Comment by adnandogar** [comment]
php artisan larasearch:paths --write-config Announcement

exception 'ErrorException' with message 'Argument 1 passed to Iverberk\Larasearch\Commands\PathsCommand::compilePaths() must be an instance of Illuminate\Database\Eloquent\Model, instance of Announcement given, called in /opt/lampp/htdocs/laravel/vendor/iverberk/larasearch/src/Iverberk/Larasearch/Commands/PathsCommand.php on line 59 and defined' in /opt/lampp/htdocs/laravel/vendor/iverberk/larasearch/src/Iverberk/Larasearch/Commands/PathsCommand.php:136

Please help me !

**Comment by adnandogar** [comment]
quick question , can i use larasearch without using model , lets suppose i want to use db table as 

DB::table('xyz')->searchByQuery($query)->getResults(); ? 

Please i need quick response .
