### ISSUE TITLE
Error during BulkImport

### ISSUE THREAD

**Issue by pfeiferchristopher** [iverberk/larasearch#49]
So I'm running into a strange error I haven't seen before. I re-added `var_dump($errorItems)` to the `ImportException` class and below is what I got during bulk import error:
```
[624]=>
  array(1) {
    ["index"]=>
    array(5) {
      ["_index"]=>
      string(20) "games_20141227034103"
      ["_type"]=>
      string(4) "game"
      ["_id"]=>
      string(4) "4958"
      ["status"]=>
      int(404)
      ["error"]=>
      string(61) "IndexShardMissingException[[games_20141227034103][0] missing]"
    }
  }
```

**Comment by iverberk** [comment]
With a clean reset I indeed meant to delete all indices and re-indexing. This is really strange. Is there anything obviously different with this piece of data that's being indexed? Are you able to make the bulk import work if you remove this particular data element? I'm not quite sure how to help you with this. It still seems like a Elasticsearch specific error, but maybe it's a Larasearch processing error with specific data.

**Comment by pfeiferchristopher** [comment]
I'm not sure what the problem is, it was working and now it's not. I'm currently in the middle of upgrading to Laravel 5.0 and that may break this package so I will take another look at it once I've completed the upgrade.

**Comment by nieldm** [comment]
I was having the same problem, it was because the charset of the database is different to the ES charset. To fix it use the eloquent mutator methods and apply utf8_encode() to all Text and VarChar columns. I hope this works for you

**Comment by iverberk** [comment]
@pfeiferchristopher I'm curious if you did the Laravel 5 upgrade. I'm just going to check what needs to be changed. Is it ok to close this issue for now or do you need more help?

**Comment by feenx** [comment]
I have upgraded and haven't re-implemented Elastic search yet. But go ahead
and close it. Not much needs changing if you need a hand I'm pretty
familiar with L5 now.

**Comment by iverberk** [comment]
Thanks for the feedback!
