### ISSUE TITLE
php artisan larasearch:reindex Model --relations not working. 

### ISSUE THREAD

**Issue by nirav-panchal** [iverberk/larasearch#53]
php artisan larasearch:reindex Model --relations not working,
when i wrote php artisan larasearch:paths Model --relations --write-config command its work properly but when i wrote php artisan larasearch:reindex Model --relations command
It gives error like below : 
 [BadMethodCallException]                                        
  Call to undefined method Illuminate\Database\Query\Builder::()

Thanks.

**Comment by pfeiferchristopher** [comment]
I'm not sure if it's required to be in order or not, but I've always done in this fashion
```bash
php artisan larasearch:[paths|reindex] --relations Model1 Model2
```

**Comment by nirav-panchal** [comment]
Inspite of wrote command in that order error still remain.
it gives 
[BadMethodCallException]
Call to undefined method Illuminate\Database\Query\Builder::()

**Comment by nirav-panchal** [comment]
when i run command php artisan larasearch:paths --relations Model it creates empty relation and return relation paths and when i run command for reindex it gives error as define above.

**Comment by iverberk** [comment]
Is the searchable trait included on all models that you are trying to index? Related models should only be indexed from a base model which had the searchable trait.

**Comment by gmooren** [comment]
Did you use the right Trait into your model?
I had the same problem as I accidentally used the wrong Trait which was also called 'SearchableTrait' :)

**Comment by nieldm** [comment]
Hi verify if you have the comment over the relation method

```		
/**
* @return \Illuminate\Database\Eloquent\Relations
*/
 public function other_table()
 {
        return $this->hasMany('OtheTable', 'other_id', 'id');
 }
```

**Comment by iverberk** [comment]
@nirav-panchal Any progress with this issue? Otherwise I'm going to close it.

**Comment by nirav-panchal** [comment]
yes, Finally i solved this issue. You can now close this issue.

Thanks for helping me.
