### ISSUE TITLE
Mappings are not being set the right way

### ISSUE THREAD

**Issue by gmooren** [iverberk/larasearch#55]
Hi iverberk,

After some hours struggling I found out that the mappings are not being set as they are supposed to.
I ran into this problem when I was trying to use the autocomplete and suggest search.

When indexing a model for the first time, it apparently does not set the right mappings when (auto)creating the index. For example, when is set the `es_config` variable in a searchable model:

```php
public static $__es_config = [
    'autocomplete' => ['name'],
    'suggest' => ['name'],
    'word_start' => ['name']
];
```

It does not apply this config in the index mapping when it auto creates that index. When I first set the mapping on the index manually, it works though.

Also, the wiki gives the following example in order to do a suggestion search:

```php
$results = Husband::search('query_string', ['fields' => ['name'], 'suggest' => true])->getResults();

$suggestions = $results->first()->getSuggestions(['name']);
```

However, I am getting a `Call to undefined method Iverberk\Larasearch\Response\Results::getSuggestions(['name'])` error.

This works though:

```php
$results = Husband::search('query_string', ['fields' => ['name'], 'suggest' => true]);

$suggestions = $results->getSuggestions(['name']);
```

It would be nice to have a flat array with only the suggestions as response.

**Comment by iverberk** [comment]
@gmooren the mapping not being set correctly is strange. I've never seen this before. You can reproduce this with a simple testcase?

For the suggestions, do you have an idea for the implementation? Maybe we can work something out together.

**Comment by gmooren** [comment]
Hi iverberk, seemed like something was wrong with my elasticsearch settings. Problem was on my side. Thanks though!
