### ISSUE TITLE
shouldIndex() method in dev-develop and dev-master

### ISSUE THREAD

**Issue by ramsaylee** [iverberk/larasearch#58]
Hi Iverberk,

I am using this great package to implement Elasticsearch in my Laravel project. I have a problem with the shouldIndex() method. It seems not to be used in the "dev-master" branch.

The "dev-master" branch
public function saved(Model $model)
{
       Queue::push('Iverberk\Larasearch\Jobs\ReindexJob',$this->findAffectedModels($model));
}

The "dev-develop" branch
public function saved(Model $model)
{
	if ($model::$__es_enable && $model->shouldIndex())
        {
	       Queue::push('Iverberk\Larasearch\Jobs\ReindexJob', $this->findAffectedModels($model));
        }
}

I need this method and I don't know what to do, because the "dev-develop" branch is not stable. Could you pls help?

**Comment by iverberk** [comment]
Ramsaylee, I will stabilize and tag a new release this week. I just need to create a changelog first because I made one (simple) backwards incompatible change. Expect to able to use it this week with a stable tag.

**Comment by ramsaylee** [comment]
Hi iverberk,

Looking forward to the stable tag, thanks a million, I will close this issue.

**Comment by iverberk** [comment]
I just tagged [0.8.0](https://packagist.org/packages/iverberk/larasearch#0.8.0) which has the requested functionality.
