### ISSUE TITLE
Exclude field(s) from the indexing.

### ISSUE THREAD

**Issue by melanholly** [iverberk/larasearch#59]
Hello,

Is there a way to exclude field(s) from indexing. I got already running database that I would like to index but there is a problem. I get a lot of exceptions from one of the fields while trying to reindex it using 
``php artisian larasearch:reindex -v Model``. 
The exceptions are different but the they are on one field. 
How to exclude it?

**Comment by iverberk** [comment]
@melanholly do you know about the transformable trait (it is included in the searchabletrait automatically)? If you include this trait on your model and specify the transform function you should be able to filter out the fields that you do not require or are giving you trouble.

**Comment by melanholly** [comment]
I've looked in the transformable trait code and found what to do but I don't quite get how to override the function but I have made changes to the source code of the `Iverberk\Larasearch\Index` class. In the Eloquent model I define `$searchable_fields` variable variable and check for it in the `Index::import()` function. The code is

```
        //model searchble fields
        $fields=isset($model::$searchable_fields)
            ?array_merge(['id','created_at','updated_at'],$model::$searchable_fields)
            :false;
        // Load records from the database
        $records = $model
            ->with($relations)
            ->skip($batchSize * ($batch - 1))
            ->take($batchSize);
        if($fields)
        {
            $records = $records
                ->select($fields)
                ->get();
        }
        else
        {
            $records = $records->get();
        }
```

I will make pull request for this so other people can use it.

**Comment by feenx** [comment]
I'm not entirely sure if @iverberk plans on continuing work on this project, although I hope so. But I have a found a good way to exclude specific field[s] from being index'd. In my situation I had to remove some because they were causing issues with ES. This still uses `->transform()` and allows had you set `$hiddenFromSearchIndex` property on the Model itself. It also works using dot notation to specific relation fields to hide.

``` php
    /**
     * @param bool $relations
     * @return array
     */
    public function transform($relations = false)
    {
        $relations  =   $relations ? Config::get('larasearch.paths.' . get_class($this)) : [];

        $model      =   $this->load($relations);

        array_forget($model, $this->getHiddenFromIndex());

        if ( ! empty($model->relations) )
        {
            foreach ($model->relations as $relation )
            {
                if ( $relation instanceof Collection )
                {
                    $relation->each(function($item)
                    {
                        if ( method_exists($item, 'removeHiddenFieldsFromIndex') )
                        {
                            $item->removeHiddenFieldsFromIndex();
                        }
                        else
                        {
                            array_forget($item, $this->getHiddenFromIndex());
                        }
                    });

                    break;
                }

                if ( method_exists($relation, 'removeHiddenFieldsFromIndex') )
                {
                    $relation->removeHiddenFieldsFromIndex();

                    break;
                }

                array_forget($relation, $this->getHiddenFromIndex());
            }
        }

        $model      =   $model->toArray();

        return $model;
    }

    /**
     * @return $this
     */
    public function removeHiddenFieldsFromIndex()
    {
        array_forget($this, $this->getHiddenFromIndex());

        return $this;
    }
```
