### ISSUE TITLE
PHP Fatal error:  Maximum function nesting level of '100' reached, aborting! 

### ISSUE THREAD

**Issue by bm2ilabs** [iverberk/larasearch#60]
PHP Fatal error:  Maximum function nesting level of '100' reached, aborting! in /home/vagrant/code/elasticsearch/vendor/symfony/console/Symfony/Component/Console/Input/InputDefinition.php on line 317

Hello i had this issue when i try to use Many to many relationship, i add SearchableTrait to both Models 'articles' and 'tags' when i add the articles to the path it works but when i try to add the tags it shows me this error " PHP Fatal error:  Maximum function nesting level of '100' reached, aborting! in /home/vagrant/code/elasticsearch/vendor/symfony/console/Symfony/Component/Console/Input/InputDefinition.php on line 317 "

**Comment by iverberk** [comment]
Do you by any chance have the xdebug extensions activated? I hit this limit while having the xdebug extension installed. You can increase the recursion level to 200 and see if that helps. If not you probably have a loop in your relationships. Use the annotations to avoid the loop. You can start by disabling all relationships and slowly adding more until you are satisfied and don't run into any loop.s

**Comment by bm2ilabs** [comment]
Hi @iverberk thanks for replaying , even i added to 500 the issue still occur , and i just can't figure out the issue , btw sorry this might sound  silly but how you can search in all records i mean in all indexes

**Comment by iverberk** [comment]
Is there any way for you to post the models? That's the only way that I can help you debug this. Like I said, disable all relations with @follow NEVER and start adding them one by one. Eventually you will find the loop.

**Comment by bm2ilabs** [comment]
Thanks @iverberk  i use @follow UNLESS AND @follow FROM and make it works thanks for this awesome package and for the help , u can close it

**Comment by bm2ilabs** [comment]
Thanks @iverberk i use @follow UNLESS AND @follow FROM and make it works thanks for this awesome package and for the help , u can close it

**Comment by iverberk** [comment]
Glad to hear you've worked it out! :-)

Searching over multiple indices is currently not yet possible. I (or someone else) might add this functionality when I need it.

**Comment by bm2ilabs** [comment]
i used ur package with this package for multiple indices https://github.com/freekmurze/searchindex

ur package work like magic with the indexing the only lacking is the multiple indices

**Comment by iverberk** [comment]
Searching over multiple indices should be relatively easy to add. Do you specify the indices to be searched manually? In Larasearch an index is coupled to an Eloquent model but I guess I could explore implementing something like 

`Larasearch::searchByIndices(array $indices, $query)`

What are your ideas on this? $indices would contain an array of searchable Eloquent models, so that the correct alias/index is retrieved.

**Comment by bm2ilabs** [comment]
In Elasticsearch when u specify that the index is "_all" it will automaticly search in all the indexes . 

Larasearch::searchByIndices(array $indices, $query) this will be great when u want to search in targeted indices . 

Larasearch::searchAll($query) and this will search for all the indices maybe , what you think ?
