### ISSUE TITLE
Items not reindexing

### ISSUE THREAD

**Issue by aaronflorey** [iverberk/larasearch#63]
I have the searchable trait, i have everything indexed via the artisan command, working perfect.

But when i update an item, it doesn't get reindexed. Looking in the queue logs, the reindex is being run successfully, but yet it doesn't show the changes in elasticsearch. 

I'm using dev-develop, since i had the same issue on dev-master.

Is there a way i can debug on why it isn't working?

Thanks

**Comment by aaronflorey** [comment]
Worked it out. Paths.json wasn't there. I wasn't aware that it wasn't generated automatically. I must have missed it in the documentation, or it wasn't there?

**Comment by bm2ilabs** [comment]
Yeah you have to add --write-config when u run the command for the first time.
