### ISSUE TITLE
Question about pagination and custom index

### ISSUE THREAD

**Issue by bm2ilabs** [iverberk/larasearch#64]
Hello , first of all i want to thank you for this amazing package and the hard work you put into it , i want to ask you about the pagination and if its an option , because it always return 50 results , and if its possible to custom that to a higher number , and about the index if its is possible to be a custom index. 

thank you again

**Comment by smithdp1** [comment]
I always get return max 50 also. How to fix this???

**Comment by bm2ilabs** [comment]
add in ur query [_size] and u can set it to whatever u want
