### ISSUE TITLE
Failed to connect to localhost port 9200: Connection refused

### ISSUE THREAD

**Issue by Oxbobby** [iverberk/larasearch#66]
Hi guys,

congrats on this package, it seems very easy to use and ultra fun. I do have one problem though - . when I try to <b>reindex</b> or <b>search</b>, I always get the following error:

 Failed to connect to localhost port 9200: Connection refused

I searched for 2-3 hours yesterday, but i didn't find a solution. Should I install something else as well? Do i have to do some extra configuration somewhere in order for the package to kick in and work?

Hoping you guys could help. :)

P.S. I'm using WAMP on Windows

**Comment by silvigit** [comment]
P.S. One suggestion - I have SSL set on WAMP, could there be a conflict between those two?

**Comment by kJamesy** [comment]
@borislavgit You have to install Elastic Search. There's a windows installation that runs as a service on your Windows machine. See https://github.com/salyh/elasticsearch-msi-installer/releases
After this installation, your localhost:9200 should work fine.

**Comment by Oxbobby** [comment]
@kJamesy 10x man, everything is up and running now. Sorry for the troubles :)

**Comment by adnandogar** [comment]
for linux what i have to do to fix it .

**Comment by kJamesy** [comment]
@adnandogar This guide worked for me http://blog.bekijkhet.com/2014/06/install-elasticsearch-in-ubuntu-1404.html

**Comment by adnandogar** [comment]
Thanks @kJamesy ! after installing i am getting error as 

{"error":"IndexMissingException[[announcements] missing]","status":404}

Announcement is my model name .

Any help please

**Comment by kJamesy** [comment]
Well, you have to do other things after installing! Did you do indexing?

**Comment by adnandogar** [comment]
i did but i am fail , can you please guide me , i just added in my model as 

use \Iverberk\Larasearch\Traits\SearchableTrait;

and then use from controller for search as 

$query['query']['match']['name'] = 'adnan';

$results = Announcement::searchByQuery($query)->getResults();

thanks in advanced !

**Comment by kJamesy** [comment]
You are probably safer opening a new issue. I could only help with the installation.

**Comment by adnandogar** [comment]
Can i do in very simple way without any reindex etc ? or what is the best idea please

**Comment by adnandogar** [comment]
Can you put down your lines how you use it ?

**Comment by adnandogar** [comment]
sorry , i have resolved it , 

Now 

quick question , can i use larasearch without using model , lets suppose i want to use db table as 

DB::table('xyz')->searchByQuery($query)->getResults(); ? 

Please i need quick response .
