### ISSUE TITLE
How to sort case insensitive

### ISSUE THREAD

**Issue by tomsonar** [iverberk/larasearch#67]
I know by default ElasticSearch does this sorting where uppercase characters will come first no matter what and that an analyzer with a lowercase filter could/should be used...But I'm trying to figure out how to do this with Larasearch. I see a bunch of custom analyzers defined in the config, but I'm not sure how to apply them. Specifically for case insensitive sorting.

I couldn't find anything here in the wiki, any ideas? Thanks.

**Comment by tomsonar** [comment]
Well I just modified the config so that:    

```
'{name}' => ['type' => 'string', 'index' => 'not_analyzed'],
```

became:    

```
'{name}' => ['type' => 'string', 'index' => 'analyzed'],
```

That solved my particular issue with sorting, but more info around the whole es_config stuff would be great though.

**Comment by iverberk** [comment]
Hi Tom,

The es_config stuff is really underdocumented. This is something that I intend to fix very soon. I'm glad you figured it out by yourself and sorry for the inconvenience.

**Comment by tomsonar** [comment]
No worries. Thanks for the package in the first place! It has saved time even if it takes a few hours to figure something out here and there. The weird thing is when I search `es_config` I don't see anything in GitHub repo search results, so I figured I'd ask. I know GitHub issues aren't the best place for questions.
