### ISSUE TITLE
The plugin isn't auto indexing 

### ISSUE THREAD

**Issue by bm2ilabs** [iverberk/larasearch#70]
Hello , i had this  issue for the start of using the plugin , i had to do a cron to index the tables but it consume a lot of resources .

the steps i followed are  : 
- installing , add SearchableTrait to the model , add paths using --dir and it works with more than 30 models with the relations and everything ,  

i think those are the steps please tell me if i forgot one .

Thank you

**Comment by feenx** [comment]
I believe you only run a console command to do the initial index, or if you need to completely re-index a Model.

This plugin uses Laravel's Queue system to re-index Model rows that are changed.

**Comment by bm2ilabs** [comment]
i found the issue it was because i change the queue config file and i set it wrong so the queue wasn't working now is working perfectly . thank you
