### ISSUE TITLE
Laravel 5.0 update possible?

### ISSUE THREAD

**Issue by feenx** [iverberk/larasearch#72]
I myself do not know what is needed to change in order for this to work within Laravel 5.0 but I would love to see it, I imagine it's a few method name changes or something not too much.

**Comment by thangngoc89** [comment]
I'm working on a L5 branch 
You can install and try it (using composer vcs)
https://github.com/iverberk/larasearch/pull/71

**Comment by feenx** [comment]
@thangngoc89 if you could explain the steps to do so I've be very thankful lol

**Comment by thangngoc89** [comment]
@pfeiferchristopher you can do something like this

``` js
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/thangngoc89/larasearch"
        }
    ],
    "require": {
        "iverberk/larasearch": "dev-develop"
    }
```

**Comment by feenx** [comment]
@thangngoc89 Thanks I'll give it a shot.

**Comment by thangngoc89** [comment]
@pfeiferchristopher OK. PRs welcome

**Comment by marijang** [comment]
Is it L5 Possible?

**Comment by feenx** [comment]
@marijang I'm currently using the version shown above and it is working properly for pretty much everything. I haven't been able to get on-change indexing working properly I believe it may be because of the changes to the Queue system between L4 and L5 but I haven't had time to look into it and try to create a PR to fix it.

**Comment by marijang** [comment]
Are you using lennynyktyk version?

**Comment by feenx** [comment]
@marijang no just googled it. I'm going to try it tonight.

**Comment by feenx** [comment]
@marijang how do I install that version of this package? I'm not good at version control.

**Comment by marijang** [comment]
@iverberk must approve pull request
https://github.com/iverberk/larasearch/pull/75

I will wait L5 version. This is great package. I need it for autocomplete for search users:D

Thanks @iverberk

**Comment by feenx** [comment]
@marijang by specifying the location of @thangngoc89 project I was able to install his pull requests before being approved. I can't do that with the lennynyktyk version?

**Comment by iverberk** [comment]
I just updated a bunch of stuff to make this compatible with L5. Could people check the L5 branch and see if it works within Laravel 5 installations?

**Comment by feenx** [comment]
I will in about 12 hours. I'll give it a thorough testing.

**Comment by feenx** [comment]
@iverberk I'm so terrible at using git to install specific versions. What version should I set to install the changes you want?

**Comment by thangngoc89** [comment]
@pfeiferchristopher It should be dev-L5 branch in composer

**Comment by feenx** [comment]
@thangngoc89 @iverberk Yeah I'm mean `"iverberk/larasearch": "dev-develop",` what should go where `"dev-develop"` I really don't understand how composer versions work. As for targeting specific branches or tags.

**Comment by iverberk** [comment]
@pfeiferchristopher you should add "iverberk/larasearch": "dev-L5" to your composer dependencies.

**Comment by feenx** [comment]
@iverberk okay I ran into the same issue I had previously manually fixed.

``` ssh
[ErrorException]
  Undefined index: errors
```

during the first batch. Going through the code I found this in `\Iverberk\Larasearch\Index.php`

``` php
if ($results['errors'])
```

and by changing it to

``` php
if ( array_key_exists('errors', $results) )
```

**Comment by iverberk** [comment]
I believe the bulk import should always return if there are errors or not? So how are you hitting this case? Which version of Elasticsearch are you using?

**Comment by feenx** [comment]
@iverberk no I'm not saying the bulk isn't returning properly. It seems as though there are no errors present in the `$results` when no errors occur. So by using `$results['errors']` an exception for `Undefined index: errors` is thrown. Where as with my fix it looks to see if the key `['errors']` exists within `$results` or not.

With my change shown above the entire package now works wonderfully. Artisan commands for `paths` and `reindex` with `--relations` as well as `--dir=app/Models` worked perfectly. Also, was able to text that the observer and queue jobs are queuing and firing as they should. Everything except the `$results['errors']` is working flawlessly.

**Comment by feenx** [comment]
Here's my `->bulk()` method:

``` php
public function bulk($records)
    {
        $params['index'] = $this->getName();
        $params['type'] = $this->getProxy()->getType();
        $params['body'] = $records;

        $results = self::getClient()->bulk($params);

        if ( array_key_exists('errors', $results) )
        {
            $errorItems = [];

            foreach ($results['items'] as $item)
            {
                if (array_key_exists('error', $item['index']))
                {
                    $errorItems[] = $item;
                }
            }

            throw new ImportException('Bulk import with errors', 1, $errorItems);
        }
    }
```

**Comment by feenx** [comment]
@iverberk I'm sorry I forgot to post this. But I did in fact have an older version of ES installed on my local environment and that was causing the issue. I have been using purely `dev-L5` and it's been working great.
