### ISSUE TITLE
BadMethodCallException with Laravel 5

### ISSUE THREAD

**Issue by bakerstreetsystems** [iverberk/larasearch#77]
I'm excited to start using this package as it looks awesome! I've followed the instructions in the wiki (https://github.com/iverberk/larasearch/wiki/Introduction) and my composer file has installed the latest version ("iverberk/larasearch": "0.8.*"), but when I include the 'Iverberk\Larasearch\LarasearchServiceProvider' in app.php, I get the following error:

"BadMethodCallException in ServiceProvider.php line 226: Call to undefined method [package]"

Any suggestions?

Also, the Readme.md file still says to use "iverberk/larasearch": "0.6.*" in the installation section.

**Comment by iverberk** [comment]
Are you using Laravel 4 or 5? If you are using L5 then please try to use the L5 branch in your composer.json. Let me know if this works.

**Comment by bakerstreetsystems** [comment]
I am using Laravel 5. What is the syntax to include the L5 branch? Thanks!

**Comment by bakerstreetsystems** [comment]
Never mind. I found it in one of the other threads towards the bottom (https://github.com/iverberk/larasearch/issues/72)

To make this work with Laravel 5, you need to include the following in your composer.json file:

"iverberk/larasearch": "dev-L5"
