### ISSUE TITLE
 ReflectionException

### ISSUE THREAD

**Issue by tacbephot** [iverberk/larasearch#78]
Hi there, i installed larasearch today and very excited, but when i run this command:

> php artisan larasearch:paths Husband

i got this error:

> [ReflectionException]
> Class iverberk.larasearch.proxy does not exist

Please help

**Comment by iverberk** [comment]
Did you include the service provider?

**Comment by tacbephot** [comment]
Yes i did. i think i fixed that, i dont know why, just remove some codes :( 
But i have some problems: 
First, when i try include TransformableTrait to my Model, have error showing:

> Trait method transform has not been applied, because there are collisions with other trait methods on CGCase\Models\Objects

Second is, here my Models

```
class Objects extends \Eloquent  {
   use TaggableTrait;
   use SearchableTrait;
   public function gallery() {
        return $this->hasMany('CGCase\Models\Gallery','object_id','id')->orderBy('order','asc');
  }
}
```

```
class Gallery extends \Eloquent  {
   use TaggableTrait;
   use SearchableTrait;
   public function objects() {
        return $this->belongsToMany('CGCase\Models\Objects','object_id','id');
  }
}
```

 when i try 

> php artisan larasearch:paths CGCase\Models\Objects  --relations

it's only showing:

```
{
    "paths": {
        "CGCase\\Models\\Objects": []
    },
    "reversedPaths": {
        "CGCase\\Models\\Objects": [
            ""
        ]
    }
}
```

as i see the result is telling Model Objects have no relationship with Model Gallery, right?

Please help :(
