### ISSUE TITLE
Auto indexing

### ISSUE THREAD

**Issue by smithdp1** [iverberk/larasearch#82]
I am confused on auto indexing. I cannot get it to work.

My model.

```
use Iverberk\Larasearch\Traits\SearchableTrait;

class Membership extends \Eloquent {

    // enable eleasticsearch
    use SearchableTrait;
```

This does not get auto indexed when new Membership record is posted to database. I have also seen this in docs. CallableTrait.

I have tried this on my model.

```
use Iverberk\Larasearch\Traits\SearchableTrait;
use Iverberk\Larasearch\Traits\CallableTrait;

class Membership extends \Eloquent {

    // enable eleasticsearch
    use SearchableTrait;
        use CallableTrait;
```

And get this error.

```
Trait method bootCallableTrait has not been applied, because there are collisions with other trait methods on Membership

```

How do i get Membership auto indexed when new records are posted?

**Comment by ferrydg** [comment]
The SearchableTrait already includes the CallableTrait so it doesn't need to be included again. That causes the error.

Did you include the ServiceProvider and run the paths command?

**Comment by smithdp1** [comment]
Yes I have included the ServiceProvider like so:

```
'providers' => array(

..................
'Iverberk\Larasearch\LarasearchServiceProvider',


    ),
```

I have also wrtten the path.json file to /app/config/packages/iverberk/larasearch/paths.json

```
{
    "paths": {
        "Membership": [
            "mailingAddress",
            "primaryMember"
        ]
    },
    "reversedPaths": {
        "Membership": [
            ""
        ],
        "Address": [
            "membership"
        ],
        "Member": [
            "membership"
        ]
    }
}
```

Did initial index of Membership with --relations flag. The initial search works great. But when a new membership gets posted to database and I try to search for new membership it does not find.

So I do manual reindex and then do search and it finds it. For some reason it is not auto indexing???

**Comment by smithdp1** [comment]
no help here??? Is there a function I can manually call on update or create?

**Comment by smithdp1** [comment]
do you have to use eloquent for the create methods or can you use 

```
DB::table('my_table')->inset($data)
```

**Comment by ferrydg** [comment]
Yes, you have to use eloquent.

**Comment by bm2ilabs** [comment]
i had an issue with auto indexing as well before i found that queue has an error try to see if ur queue has an error with this command 

```
php artisan queue:listen
```

try to see if errors are showing

**Comment by smithdp1** [comment]
Yes i am using eloquent with:

```
$membership = new Membership;

$membership->save();
```

I also just have the stock /app/config/queue.php file. I have not touched it. Am I supposed to do something with this file?

I tried:

```
php artisan queue:listen
```

It does nothing except wait....I tried to post a new membership and it did nothing. Terminal is just in wait state.

Thank you very much for the help and giving this your attention.

**Comment by feenx** [comment]
@smithdp1 If you haven't changed anything in `config/queue.php` then it should be executing queue jobs asynchronously meaning at page load. So whenever something is done to change a Model it should be  flagged to the queue system to be re-indexed, and should be done on the page load.

If this is not occurring I would look at your `laravel.log` after changing something and see if it's throwing any errors causing the `ReindexJob` to stop firing.

Another thing it could be is that you are not "saving" the paths config. When running

``` php
php artisan larasearch:paths --relations
```

you must also use `--write-config` to actually save the paths configuration which is what is used to determine what models to re-index upon changes. It should look like this

``` php
php artisan larasearch:paths --relations --write-config
```

Not using `--write-config` is just so it outputs the structure and you can check it.

**Comment by smithdp1** [comment]
@pfeiferchristopher
thanks for the advice. I have properly written the paths.json file and it has been saved to:

```
/app/config/packages/iverberk/larasearch/paths.json
```

I have also checked the logs and no errors there. I was wondering is there a way to call something like the below manually?

```
$membership = new Membership;

$membership->save();

$membership->reIndex();
```

Just running out of options and trying to maybe force it somehow. 
Thanks again for everybody's help!

**Comment by smithdp1** [comment]
Help anybody???

**Comment by smithdp1** [comment]
Fiannly found out that jobs were being sent to queue but not being processed. I am on an ubuntu server and added this to to /etc/init/myqueue.conf

```
description "work queue"
start on filesystem
stop on runlevel [!2345]
respawn
respawn limit 5 2
script
exec /usr/bin/php /path/to/laravel/artisan queue:listen
end script
```

Then start the queue: "start myqueue". That's it, it will be automatically monitored and restarted in case of crash. No need for external daemons.
