### ISSUE TITLE
Class not found when using larasearch:paths

### ISSUE THREAD

**Issue by paulocoghi** [iverberk/larasearch#84]
First of all, congratulations for the great work!

**Short description of the issue:**
`php artisan larasearch:paths --relations Company` results in:
`PHP Fatal error:  Class 'Company' not found`

Also, `php artisan larasearch:paths --relations --dir=app/Models` results in `No models found.`

**Software Versions:**
Laravel Framework: **`5.0.31`**
Larasearch: **`dev-L5`** _(updated on May 20, 2015)_
Elasticsearch: **`1.5.2`** _(perfectly responding to `curl http://localhost:9200`)_

---

**Details:**

A simple Model example:

``` php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

// Larasearch Searchable Trait
use Iverberk\Larasearch\Traits\SearchableTrait;

class Company extends Model {

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function address()
    {
        return $this->morphOne('App\Address', 'addressable');
    }

    public function contact()
    {
        return $this->morphOne('App\Contact', 'contactable');
    }

    public function slug()
    {
        return $this->morphOne('App\Slug', 'slugable');
    }

}
```

When I try to generate paths for a specific model using: `php artisan larasearch:paths --relations Company` the result is a fatal error:

```
PHP Fatal error:  Class 'Company' not found in /home/api/api/vendor/iverberk/larasearch/src/Iverberk/Larasearch/Commands/PathsCommand.php on line 59
```

This is an already running Laravel app and, since this is my first time with Larasearch, I don't know how to solve this issue.

**Comment by paulocoghi** [comment]
Issue solved. The problem is with the namespace.

Just used: `php artisan larasearch:paths --relations 'App\Company'` and voilá

**Comment by oguzcicek** [comment]
i have same issue , how did you solve it ? My problem is 
`php artisan larasearch:paths --dir='app/Models'  City`
 but it gives this error :  `[Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'City' not found`

**Comment by oguzcicek** [comment]
it works with : `php artisan larasearch:paths  App\\Models\\City`
